name: CoreLobby
version: beta_1.0
author: EdmineCoreTeam
main: fr.edminecoreteam.corelobby.Core
commands:
  grouptag:
    description: Commande grouptag
  game:
    description: Commande game
  link:
    description: Commande link